# Shoe API

### GET all shoes in api
GET http://localhost:3000/api/shoes

### GET shoes by brand name adidas
GET http://localhost:3000/api/shoes/brand/Adidas

### GET shoes by brand name nike 
GET http://localhost:3000/api/shoes/brand/Nike

### GET shoes by size 
GET http://localhost:3000/api/shoes/size/5

### GET shoes by brand and size 
GET http://localhost:3000/api/shoes/brand/Puma/size/5

### GEt shoes by brand, size and color 
GET http://localhost:3000/api/shoes/brand/Puma/size/3/color/Grey

### GET shoe spec
GET http://localhost:3000/api/shoes/shoe/ADIMATIC%20SHOES

###
POST http://localhost:3000/api/shoes
Content-Type: application/json

{
   "shoename":"ADIMATIC SHOES",
    "color":"Charcoal Solid Grey / Stone / Dgh Solid Grey",
    "brand":"Adidas","price":"2799.00",
    "size":7,
    "stock":3,
    "image_url":"https://assets.adidas.com/images/w_1880,f_auto,q_auto/985cbe5bb82646cd826aaf3400b23d87_9366/HP6771_06_standard.jpg",
    "gender":"Men",
    "size_url":""
}


### GET shoe by Iid 
GET http://localhost:3000/api/shoes/2

################################################

# User APi 

### POST a user 
POST http://localhost:3000/users
Content-Type: application/json

{
    "username":"aPl",
    "email":"aO",
    "user_password":"Ua"
}

### GET a user 
GET http://localhost:3000/users

###
GET http://localhost:3000/api/user/Mercy

### POST a username to check a user from data base
POST http://localhost:3000/users/user
Content-Type: application/json

{
    "username" : "Mercy",
    "user_password": "1234"

}


################################################

# Oders Api

### Create a cart
GET http://localhost:3000/api/order-cart/create?username=Mercyfulll


###
POST http://localhost:3000/api/order
Content-Type: application/json

{
    "username" : "Mercy",
    "shoeid": 21
}

###
GET http://localhost:3000/api/order


